In [1]:
import numpy as np

In [2]:
# Numpy ndarray
a = np.array([1,2,3])
print(a, type(a))

[1 2 3] <class 'numpy.ndarray'>


In [5]:
# List와 비교
l = [1,2,3]
a = np.array(l)
print(l, type(l))
print(a, type(a))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [7]:
for item in l:
  print(item)

1
2
3


In [8]:
for item in a:
  print(item)

1
2
3


In [9]:
# 데이터 추가
l.append(4)
print(l)

[1, 2, 3, 4]


In [11]:
# np.array 데이터 추가
a = np.append(a, 4)
print(a)

[1 2 3 4]


In [12]:
# list 데이터 추가
l = l + [5]
print(l)

[1, 2, 3, 4, 5]


In [13]:
# List의 모든 원소를 2배를 만들기
l = [1,2,3]
i2 = []
for item in l:
  i2.append(item*2)
print(i2)

[2, 4, 6]


In [14]:
# ndarray의 모든 원소를 2배로 만들기
a = np.array(l)
a2 = a*2
print(a2)

[2 4 6]


In [15]:
# List는 원소가 두배가 된다
l * 2

[1, 2, 3, 1, 2, 3]

In [19]:
# 배열
a = np.array([1,2,3])
print(a)
print('type : {}\nndim : {}\nshape : {}\ndtype : {}'.format(type(a), a.ndim, a.shape, a.dtype))

[1 2 3]
type : <class 'numpy.ndarray'>
ndim : 1
shape : (3,)
dtype : int64


In [23]:
# asarray : numpy array로 변환
b = np.asarray(a)
print(b)

[9 2 3]


In [24]:
# b 요소 변환 a도 같이 변환
b[0] = 9
print(a)
print(b)

[9 2 3]
[9 2 3]


In [25]:
# 인자가 np.array일 경우에 반환, 아닐경우 새로운 np.array로 반환
c = [1,2,3]
d = np.asarray(c)
d[0] = 8
print(c)
print(d)

[1, 2, 3]
[8 2 3]


In [26]:
# 3*4 0인 배열
a = np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [27]:
# 5*2 1인 배열
b = np.ones((5,2))
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [28]:
# 2*3 4인 배열
c = np.full((2,3), 4)
print(c)

[[4 4 4]
 [4 4 4]]


In [29]:
# 2*3 빈 배열 생성 -> 배열 내용은 이미 존재한 값으로 랜덤
d = np.empty((2,3))
print(d)

[[4.77739272e-310 0.00000000e+000 5.29279385e+199]
 [6.45598269e+170 1.33717014e-152 2.19527311e-152]]


In [31]:
# a 같은 배열 즉 3*4인 배열로 생성
e = np.zeros_like(a) # 0으로
f = np.ones_like(a) # 1으로
g = np.full_like(a, 2) # 2으로
h = np.empty_like(a) # 빈 배열으로
print(e)
print('')
print(f)
print('')
print(g)
print('')
print(h)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]

[[4.77739268e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [48]:
# 항등 행렬
# eye : 대각선 행렬, identity : 단위 행렬 생성(행렬의 크기)
i = np.eye(3)
j = np.identity(3)
print(i)
print('')
print(j)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [49]:
# eye는 k로 이동 할 수 있음 - 왼, + 오
i2 = np.eye(3, k=1) * 2 # 곱하기로 숫자 변환
print(i2 )

[[0. 2. 0.]
 [0. 0. 2.]
 [0. 0. 0.]]


In [50]:
# 0~9까지 배열 생성
k = np.arange(10)
print(k)

[0 1 2 3 4 5 6 7 8 9]


In [51]:
# 2*2인 랜덤 배열 생성(0~1의 랜덤한 값)
l = np.random.rand(2,2)
print(l)

[[0.90404081 0.40344794]
 [0.63169238 0.25699806]]


In [52]:
# 2*2인 평균이 1이고 표준편차 1인 정규분포의 랜덤 배열 생성
m = np.random.randn(2,2)
print(m)

[[ 0.93382772  1.08404168]
 [-0.83000549 -0.82461578]]


In [53]:
# 배열의 dtype
a = np.array([1, 2, 3])
b = np.array([1, 2, 3], dtype=np.float64)
c = np.array([1, 2, 3], dtype=np.int32)

print(a.dtype, b.dtype, c.dtype)

int64 float64 int32


In [54]:
d = np.array([1, 2, 3], dtype='i1')
e = np.array([1, 2, 3], dtype='i2')
f = np.array([1, 2, 3], dtype='i4')
g = np.array([1, 2, 3], dtype='i8')

print(d.dtype, e.dtype, f.dtype, g.dtype)

int8 int16 int32 int64


In [55]:
d = np.array([1, 2, 3], dtype='u1')
e = np.array([1, 2, 3], dtype='u2')
f = np.array([1, 2, 3], dtype='u4')
g = np.array([1, 2, 3], dtype='u8')

print(d.dtype, e.dtype, f.dtype, g.dtype)

uint8 uint16 uint32 uint64


In [56]:
h = np.array([1, 2, 3], dtype='f2')
i = np.array([1, 2, 3], dtype='f4')
j = np.array([1, 2, 3], dtype='f8')
k = np.array([1, 2, 3], dtype='f16')

print(h.dtype, i.dtype, j.dtype, k.dtype)

float16 float32 float64 float128


In [58]:
h = np.array([1, 2, 3], dtype='f2')
i = np.array([1, 2, 3], dtype='f')
j = np.array([1, 2, 3], dtype='d')
k = np.array([1, 2, 3], dtype='g')

print(h.dtype, i.dtype, j.dtype, k.dtype)

float16 float32 float64 float128


In [59]:
i = i.astype(np.int32)
print(i.dtype)

int32


In [60]:
j = j.astype(i.dtype)
print(j.dtype)

int32


In [61]:
# 배열 indexing, slicing
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [62]:
# indexing
print(a[5])

5


In [63]:
# slicing
print(a[5:8])

[5 6 7]


In [64]:
print(a[-1])

9


In [65]:
print(a[7:-1])

[7 8]


In [66]:
a[5:8] = 10
print(a)

[ 0  1  2  3  4 10 10 10  8  9]


In [68]:
# indexcing, slicing의 차이
b = np.arange(1, 13)
# b = b.reshape(3, 4)
print(b)
print('')
print(b.shape)
print('')
print(b.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

(12,)

1


In [71]:
indexing = b[1]
slicing = b[1:2]
print('indexing : {}\nshape : {}\nndim :{}'.format(indexing, indexing.shape, indexing.ndim))
print('')
print('slicing : {}\nshape : {}\nndim : {}'.format(slicing, slicing.shape, slicing.ndim))

indexing : 2
shape : ()
ndim :0

slicing : [2]
shape : (1,)
ndim : 1


In [72]:
# 배열 변환
b = b.reshape(3, 4)
print(b)
print('')
print(b.shape)
print('')
print(b.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

(3, 4)

2


In [73]:
row_r1 = b[1, :] # indexing # 차원 감소
row_r2 = b[1:2, :] # sliceing
print(row_r1, row_r1.shape, row_r1.ndim)
print(row_r2, row_r2.shape, row_r2.ndim)

[5 6 7 8] (4,) 1
[[5 6 7 8]] (1, 4) 2


In [74]:
c = np.arange(24).reshape(2,3,4)
print(c)
print(c.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)


In [76]:
print(c[:,:,:1])
print('')
print(c[...,:1])

[[[ 0]
  [ 4]
  [ 8]]

 [[12]
  [16]
  [20]]]

[[[ 0]
  [ 4]
  [ 8]]

 [[12]
  [16]
  [20]]]


In [78]:
print(c[0:1])
print('')
print(c[0::-1])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


In [80]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [81]:
# boolean indexing
bool_idx = (c > 10)
print(bool_idx)

[[[False False False False]
  [False False False False]
  [False False False  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]]


In [82]:
print(c[bool_idx])

[11 12 13 14 15 16 17 18 19 20 21 22 23]


In [84]:
# fancy indexing
d = np.arange(8).reshape(8,-1)
print(d, d.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]] (8, 1)


In [85]:
d = np.hstack((d, d, d, d))
print(d, d.shape)

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]] (8, 4)


In [86]:
print(d[[3, 5, 1, 0]])

[[3 3 3 3]
 [5 5 5 5]
 [1 1 1 1]
 [0 0 0 0]]


In [87]:
print(d[[-3, -5, -7]])

[[5 5 5 5]
 [3 3 3 3]
 [1 1 1 1]]


In [88]:
e = np.arange(32).reshape(8,4)
print(e, e.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]] (8, 4)


In [89]:
print(e[[1,5,7,2], [0,3,1,2]])

[ 4 23 29 10]


In [90]:
print(e[[1,5,7,2]][:, [0,3,1,2]])

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [92]:
# transpose 축 변경
f = np.arange(16).reshape(2,2,4)
print(f, f.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4)


In [93]:
# 차원의 순서 변경
print(f.transpose(1, 0, 2))

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [94]:
# 첫번째 축, 두번째 축 서로 교환
print(f.swapaxes(0, 1))

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [96]:
# Numpy 연산
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[5,6], [7,8]], dtype=np.float64)
print(x)
print('')
print(y)

[[1. 2.]
 [3. 4.]]

[[5. 6.]
 [7. 8.]]


In [98]:
# add
print(x + y)
print('')
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]

[[ 6.  8.]
 [10. 12.]]


In [99]:
# sub
print(x - y)
print('')
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]

[[-4. -4.]
 [-4. -4.]]


In [100]:
# multiful
print(x * y)
print('')
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]

[[ 5. 12.]
 [21. 32.]]


In [101]:
# divide
print(x / y)
print('')
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [103]:
# 행렬 곱
print(x @ y)
print('')
print(np.matmul(x, y))

[[19. 22.]
 [43. 50.]]

[[19. 22.]
 [43. 50.]]


In [104]:
z = np.arange(1, 11).reshape(2, 5)
print(z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [105]:
print(np.sum(z))

55


In [106]:
sum1 = np.sum(z, axis=0) # 0번축
sum2 = np.sum(z, axis=1) # 1번축
sum3 = np.sum(z, axis=-1) # 0, 1 1번축
print(sum1, sum1.shape)
print(sum2, sum2.shape)
print(sum3, sum3.shape)

[ 7  9 11 13 15] (5,)
[15 40] (2,)
[15 40] (2,)


여기서 축(axis)은 각 배열의 차원에 해당되는 index 입니다.

axis=0에 대하여 sum을 하라는 것은 0번 축 혹은 차원이 없어지는 방향으로 원소들을 모두 더하라는 얘기입니다.

즉, 위 예에서 sum1의 경우, z[0,:]+z[1,:]의 연산을 하라는 의미이고,

sum2의 경우에는 z[:,0]+z[:,1]+z[:,2]+z[:,3]+z[:,4]의 연산을 하라는 의미입니다.

In [109]:
# sum1
print(z[0,:])
print(z[1,:])
print(z[0,:] + z[1,:])

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 7  9 11 13 15]


In [108]:
# sum2
print(z[:,0] + z[:,1] + z[:,2] + z[:,3] + z[:,4])

[15 40]


In [110]:
# Broadcasting
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
y = np.array([1,0,2])

In [113]:
print(x, x.shape)
print('')
print(y, y.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)

[1 0 2] (3,)


In [112]:
z = x + y
print(z, z.shape)

[[ 2  2  5]
 [ 5  5  8]
 [ 8  8 11]
 [11 11 14]] (4, 3)


두 개의 배열을 브로드캐스팅하는 것은 다음 규칙을 따릅니다.

1. 배열의 랭크가 같지 않으면 두 모양이 같은 길이가 될 때까지 배열의 낮은 랭크쪽에 1을 붙입니다.
2. 두 배열은 차원에서 크기가 같거나 배열 중 하나의 차원에 크기가 1 인 경우 차원에서 호환 가능하다고 합니다.
3. 배열은 모든 차원에서 호환되면 함께 broadcast 될 수 있습니다.
4. Broadcast 후 각 배열은 두 개의 입력 배열의 요소 모양 최대 개수와 동일한 모양을 가진 것처럼 동작합니다.
5. 한 배열의 크기가 1이고 다른 배열의 크기가 1보다 큰 차원에서 첫 번째 배열은 마치 해당 차원을 따라 복사 된 것처럼 작동합니다

실제로 동작하는 방식을 생각해 봅시다.

1. A와 B의 모양을 생각합니다.
2. 두 배열이 len(A.shape) == len(B.shape)인지 확인을 합니다.
3. 같지 않은 경우에는 두 배열의 모양 길이가 같아질때까지 적은 쪽의 shape 앞에 1 을 추가해 줍니다.
- 예: (5,3)–>(1,5,3)
4. shape이 1인 곳은 복사가 됩니다.
- 예: shape의 변화는 아래와 같게 될겁니다.
- (5, 3)+(3,)
- (5, 3)+(1, 3)
- (5, 3) + (5, 3)
- (5, 3)

이 설명이 이해가되지 않으면 문서 또는 이 설명을 읽으십시오.

https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc

Broadcasting을 지원하는 함수들을 보편 함수라고합니다. 이 문서에서 모든 보편 함수 목록을 찾을 수 있습니다.
https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs

In [115]:
x = np.array([1,2,3]).reshape(1,3)
y = np.array([4,5]).reshape(1,2)
print(x, x.shape)
print('')
print(y, y.shape)

[[1 2 3]] (1, 3)

[[4 5]] (1, 2)


In [ ]:
# broadcasting 조건에 맞지 않음
print(x + y)

In [117]:
y = y.swapaxes(0, 1)
print(y, y.shape)

[[4]
 [5]] (2, 1)


In [118]:
# broadcasting 발생
print(x + y)

[[5 6 7]
 [6 7 8]]


In [119]:
# shape 변경
a = np.arange(24).reshape(2,3,4)
print(a, a.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] (2, 3, 4)


In [120]:
a = a.reshape(4, -1)
print(a, a.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]] (4, 6)


In [121]:
a = a[..., np.newaxis]
print(a, a.shape)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]
  [16]
  [17]]

 [[18]
  [19]
  [20]
  [21]
  [22]
  [23]]] (4, 6, 1)


In [122]:
a = a.reshape(4, 6)
a = np.expand_dims(a, axis=0)
print(a, a.shape)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]] (1, 4, 6)


In [123]:
a = a.reshape(4, 6)
a = np.expand_dims(a, axis=1)
print(a, a.shape)

[[[ 0  1  2  3  4  5]]

 [[ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]]

 [[18 19 20 21 22 23]]] (4, 1, 6)


In [124]:
b = a.copy()
print(b, b.shape)

[[[ 0  1  2  3  4  5]]

 [[ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]]

 [[18 19 20 21 22 23]]] (4, 1, 6)


In [125]:
c = np.concatenate((a, b), axis=-1)
print(c, c.shape)

[[[ 0  1  2  3  4  5  0  1  2  3  4  5]]

 [[ 6  7  8  9 10 11  6  7  8  9 10 11]]

 [[12 13 14 15 16 17 12 13 14 15 16 17]]

 [[18 19 20 21 22 23 18 19 20 21 22 23]]] (4, 1, 12)


In [126]:
c = np.concatenate((a, b), axis=0)
print(c, c.shape)

[[[ 0  1  2  3  4  5]]

 [[ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]]

 [[18 19 20 21 22 23]]

 [[ 0  1  2  3  4  5]]

 [[ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]]

 [[18 19 20 21 22 23]]] (8, 1, 6)


In [127]:
d = np.stack((a, b), axis=-1)
print(d, d.shape)

[[[[ 0  0]
   [ 1  1]
   [ 2  2]
   [ 3  3]
   [ 4  4]
   [ 5  5]]]


 [[[ 6  6]
   [ 7  7]
   [ 8  8]
   [ 9  9]
   [10 10]
   [11 11]]]


 [[[12 12]
   [13 13]
   [14 14]
   [15 15]
   [16 16]
   [17 17]]]


 [[[18 18]
   [19 19]
   [20 20]
   [21 21]
   [22 22]
   [23 23]]]] (4, 1, 6, 2)


In [128]:
d = np.stack((a, b), axis=0)
print(d, d.shape)

[[[[ 0  1  2  3  4  5]]

  [[ 6  7  8  9 10 11]]

  [[12 13 14 15 16 17]]

  [[18 19 20 21 22 23]]]


 [[[ 0  1  2  3  4  5]]

  [[ 6  7  8  9 10 11]]

  [[12 13 14 15 16 17]]

  [[18 19 20 21 22 23]]]] (2, 4, 1, 6)
